export const ActionTypes = {
   SET_PRODUCT: "SET_PRODUCT",
   SELECTED_PRODUCT: "SELECTED_PRODCUT",
   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
   ADD_TO_CART: "ADD_TO_CART",
   REMOVE_FROM_CART: "REMOVE_FROM_CART",
   ITEM_QUANTITY: "ITEM_QUANTITY",
};
